version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-cda_projet}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-}
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306" 
    environment:
      - MYSQL_DATABASE=${DB_NAME:-cda_projet}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  mysql_data:
